config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users

  resources :users, only: [:new, :show] do
    resources :items, only: [:create, :destroy]
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :items, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]
  before_action :config_devise_params, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  private

  def config_devise_params
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @user = current_user
    @item = @user.items.new(item_params)
    @new_item = Item.new

    if @item.save
      flash[:notice] = "Item saved successfully."
    else
      flash[:alert] = "Item failed to save."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @user = current_user
    @item = @user.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item was deleted successfully."
    else
      flash.now[:alert] = "There was an error deleting the item."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end


  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = current_user
     @items = current_user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_items_empty?
    @items == nil
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="col-md-12 new-item">
 <%= form_for [current_user, item], remote: true do |f| %>
   <div class="form-group">
     <%= f.label "Add an Item" %>
     <%= f.text_field :name, class: 'form-control', placeholder: "Enter item name" %>
   </div>

   <div class="form-group">
     <%= f.submit "Add Item", class: 'btn btn-default' %>
   </div>
 <% end %>
</div>

app/views/items/_item.html.erb
<% if current_user.items == nil %>
  <p>No Tasks</p>
<% else %>
  <p class="item" id="item-<%= item.id %>">
    <%= item.name %> have <%= distance_of_time_in_words(item.created_at, 7.days.from_now, include_seconds: false) %> left
    <%= link_to "", [item.user, item], method: :delete, remote: true, class: 'fa fa-thumbs-up', data: {confirm: "Have you completed this task?"} %>
  </p>
<% end %>

app/views/items/create.js.erb
<% if @item.valid? %>
  $('.js-items').append("<%= escape_javascript(render(@item)) %>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { item: @new_item}) %>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { item: Item.new}) %>");
<% end %>

app/views/items/destroy.js.erb
$("#item-" + <%= @item.id %>).hide();

app/views/layouts/_header.html.erb
<div class="navbar-app">
 <ol class="nav">
    <%= link_to image_tag("logo.png"), welcome_index_path %>
    <div class="user-control">
      <% if user_signed_in? %>
         <%= link_to current_user.username, user_path(current_user)%>
         <div class="btn-group btn-user">
           <%= image_tag current_user.avatar_url(35), class: "gravatar" %>
           <button class="pull-right avatar-btn" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <span class="caret" style="color:white;"></span>
             <span class="sr-only">Toggle Dropdown</span>
           </button>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'%></li>
            </ul>
         </div>
       <% else %>
         <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %>
         <%= link_to "Log In", new_user_session_path, :class => 'navbar-link' %>
      <% end %>
    </div>
 </ol>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimesUp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div>

    <% if flash[:notice] %>
       <div class="alert-wrapper">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:error] %>
       <div class="alert-wrapper">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert-wrapper">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<div class="user-page">
  <section class="user-heading">
     <% avatar_url = @user.avatar_url(100) %>
     <% if avatar_url %>
    <div class="avatar-img">
      <%= image_tag avatar_url, class: 'media-object' %>
    </div>
     <% end %>
    <div>
      <h1>Hello <span style="color:#00ffcb;"><%= @user.username %></span></h1>
      <h2>Here's Your To Do List</h2>
    </div>
  </section>

  <section class="container task">
    <div class="col-md-12">
    <h1><i class="fa fa-check-square-o" aria-hidden="true"></i>Tasks</h1>
      <%= render partial: 'items/form', locals: {item: Item.new} %>
    </div>
  </section>

  <section class="container list">
    <h1><i class="fa fa-tasks" aria-hidden="true"></i>Things To Do (<%= current_user.items.count%>)</h1>
    <div class="js-items">
      <%= render current_user.items %>
    </div>
  </section>
</div>

app/views/welcome/index.html.erb
<div class="learn">
  <section>
    <h1>We Want To Help You Be More <span style="color: #00ffcb;">Productive</span></h1>
    <p>  Times<span style="color: #00ffcb;">Up</span> is a to do list application designed to help you keep track of daily or weekly tasks.
         Tasks that are not completed within a week will be automatically removed. Sign Up for a free
         account today!</p>
  </section>
</div>